# Runs every 10 minutes and POSTs to your app's /internal/refresh with a bearer token
# Requires two repository secrets: DEPLOY_URL and REFRESH_TOKEN
on:
  schedule:
    - cron: '*/10 * * * *'   # every 10 minutes
  workflow_dispatch:

jobs:
  refresh-csv:
    runs-on: ubuntu-latest
    steps:
      - name: Call refresh endpoint
        env:
          DEPLOY_URL: ${{ secrets.DEPLOY_URL }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        run: |
          if [ -z "$DEPLOY_URL" ] || [ -z "$REFRESH_TOKEN" ]; then
            echo "Missing DEPLOY_URL or REFRESH_TOKEN secrets"
            exit 1
          fi
          echo "Posting to ${DEPLOY_URL}/internal/refresh"
          http_code=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
            -H "Authorization: Bearer ${REFRESH_TOKEN}" \
            "${DEPLOY_URL}/internal/refresh")
          echo "HTTP code: $http_code"
          if [ "$http_code" != "200" ]; then
            echo "Refresh endpoint returned non-OK: $http_code"
            exit 1
          fi
